name: 🚀 Deploy Backend to Render via API

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📤 Trigger Deploy on Render
        run: |
          curl -X POST https://api.render.com/v1/services/srv-d1f95vidbo4c739oq290/deploys \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}'
